services:
  graph-node:
    image: graphprotocol/graph-node
    healthcheck:
      test: [ "CMD", "sh", "-c", "nc -z localhost 8000" ]
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
      - "8030:8030"
      - "8040:8040"
    depends_on:
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env.local before running docker-compose}
      postgres_db: graph-node
      ethereum: "mainnet:https://rpc-gate.autonolas.tech/ethereum-rpc/ --ethereum-rpc base:https://rpc-gate.autonolas.tech/base-rpc/ --ethereum-rpc gnosis:https://rpc-gate.autonolas.tech/gnosis-rpc/ --ethereum-rpc mode-mainnet:https://mainnet.mode-mainnet.network/"
      ipfs: ${IPFS_URL:-https://registry.autonolas.tech}
      GRAPH_LOG: ${GRAPH_LOG:-debug}
      GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: "true"
      GRAPH_START_BLOCK: ${GRAPH_START_BLOCK:-0}
      GRAPH_ETHEREUM_GENESIS_BLOCK_NUMBER: ${GRAPH_ETHEREUM_GENESIS_BLOCK_NUMBER:-0}
      GRAPH_STORE_WRITE_BATCH_DURATION: 0
      GRAPH_STORE_WRITE_BATCH_SIZE: 0
      ETHEREUM_POLLING_INTERVAL: ${ETHEREUM_POLLING_INTERVAL:-1000}

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    command: [ "postgres", "-cshared_preload_libraries=pg_stat_statements" ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD in .env.local before running docker-compose}
      POSTGRES_DB: graph-node
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
