enum packageType {
  protocol
  connection
  contract
  skill
  agent
  service
  unknown
}

type Unit @entity(immutable: true) {
  id: Bytes! # Unique ID for the record
  tokenId: BigInt! # Token ID of the minted component
  packageType: packageType! # Component type
  packageHash: String! # IPFS hash of the package
  description: String! # Package description
  image: String! # Image hash
  owner: String! # Owner address
  metadataHash: String! # Metadata file hash
  publicId: String! # Public ID of the package
}
