enum packageType {
  protocol
  connection
  contract
  skill
  agent
  service
  unknown
}

type Unit @entity(immutable: true) {
  id: Bytes! # Unique ID for the record
  tokenId: BigInt! # Token ID of the minted component
  packageType: packageType! # Component type
  packageHash: String! # IPFS hash of the package
  description: String! # Package description
  image: String! # Image hash
  owner: String! # Owner address
  metadataHash: String! # Metadata file hash
  publicId: String! # Public ID of the package
}

type Service @entity {
  id: Bytes! # Unique ID for the record
  state: BigInt! # Current state of the service
  serviceId: BigInt! # Service ID
  agentIds: [BigInt!] # List of agent IDs
  configHash: String! # Config hash for the service
  threshold: BigInt! # Threshold value
  securityDeposit: BigInt! # Security deposit
  numberOfInstances: BigInt! # Number of instances
  maxNumberOfInstances: BigInt! # Number of instances
  multisig: String! # Multisig address
  instances: [String!] # List of agent instances
}