module.exports = class Data1788514727199 {
    name = 'Data1788514727199'

    async up(db) {
        await db.query(`CREATE TABLE "agent_safe" ("id" character varying NOT NULL, "created_timestamp" numeric NOT NULL, "master_safe_id" character varying, "service_id" character varying, CONSTRAINT "PK_5b0c6b118656349610d78985dc0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_agent_safe_master_safe_15dfcbff" ON "agent_safe" ("master_safe_id") `)
        await db.query(`CREATE INDEX "idx_agent_safe_service_c1d14b83" ON "agent_safe" ("service_id") `)
        await db.query(`CREATE TABLE "staking_contract" ("id" character varying NOT NULL, "implementation" text NOT NULL, "min_staking_deposit" numeric NOT NULL, "num_agent_instances" numeric NOT NULL, "created_block" numeric NOT NULL, "created_timestamp" numeric NOT NULL, CONSTRAINT "PK_692a716f40eadb56ebf963eeee6" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "service" ("id" character varying NOT NULL, "service_id" numeric NOT NULL, "agent_ids" integer array NOT NULL, "operators" text array NOT NULL, "state" text NOT NULL, "nft_custodian" text, "total_olas_rewards_claimed" numeric NOT NULL, "registered_timestamp" numeric NOT NULL, "updated_timestamp" numeric NOT NULL, "master_safe_id" character varying, "agent_safe_id" character varying, "current_staking_contract_id" character varying, CONSTRAINT "PK_85a21558c006647cd76fdce044b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_service_master_safe_8b79bdf7" ON "service" ("master_safe_id") `)
        await db.query(`CREATE INDEX "idx_service_agent_safe_a2926dff" ON "service" ("agent_safe_id") `)
        await db.query(`CREATE INDEX "idx_service_current_staking_contract_8fef2861" ON "service" ("current_staking_contract_id") `)
        await db.query(`CREATE TABLE "master_safe" ("id" character varying NOT NULL, "network" text NOT NULL, "master_eoa" text NOT NULL, "owners" text array NOT NULL, "threshold" numeric NOT NULL, "first_seen_timestamp" numeric NOT NULL, "first_seen_block" numeric NOT NULL, "history_floor_block" numeric NOT NULL, "history_floor_timestamp" numeric NOT NULL, "last_activity_timestamp" numeric NOT NULL, "setup_transfer_seen" boolean NOT NULL, CONSTRAINT "PK_82d140711d726430735f2a31b74" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "agent_funding_event" ("id" character varying NOT NULL, "tx_hash" text NOT NULL, "block_timestamp" numeric NOT NULL, "total_native_amount" numeric NOT NULL, "total_olas_amount" numeric NOT NULL, "service_id" character varying, "master_safe_id" character varying, CONSTRAINT "PK_b9d1034a9a5a475262afb673805" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_agent_funding_event_service_5b5efd90" ON "agent_funding_event" ("service_id") `)
        await db.query(`CREATE INDEX "idx_agent_funding_event_master_safe_6d6a8407" ON "agent_funding_event" ("master_safe_id") `)
        await db.query(`CREATE TABLE "funds_movement" ("id" character varying NOT NULL, "epoch" numeric, "category" character varying(20) NOT NULL, "source" character varying(12) NOT NULL, "token" text, "amount" numeric NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "service_id" character varying, "master_safe_id" character varying, "agent_safe_id" character varying, "staking_contract_id" character varying, "agent_funding_event_id" character varying, CONSTRAINT "PK_9df95b9995868c7ef2851b94baa" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_funds_movement_service_00889d75" ON "funds_movement" ("service_id") `)
        await db.query(`CREATE INDEX "idx_funds_movement_master_safe_e85e0274" ON "funds_movement" ("master_safe_id") `)
        await db.query(`CREATE INDEX "idx_funds_movement_agent_safe_8baac439" ON "funds_movement" ("agent_safe_id") `)
        await db.query(`CREATE INDEX "idx_funds_movement_staking_contract_5b8e460e" ON "funds_movement" ("staking_contract_id") `)
        await db.query(`CREATE INDEX "idx_funds_movement_agent_funding_event_e58d176e" ON "funds_movement" ("agent_funding_event_id") `)
        await db.query(`CREATE TABLE "bond_movement" ("id" character varying NOT NULL, "category" character varying(20) NOT NULL, "source" character varying(12) NOT NULL, "bond_type" character varying(16), "token" text, "amount" numeric NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "service_id" character varying, "master_safe_id" character varying, "agent_safe_id" character varying, CONSTRAINT "PK_4fa2299add243a9c196783a0706" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_bond_movement_service_09b070cf" ON "bond_movement" ("service_id") `)
        await db.query(`CREATE INDEX "idx_bond_movement_master_safe_46f5ecad" ON "bond_movement" ("master_safe_id") `)
        await db.query(`CREATE INDEX "idx_bond_movement_agent_safe_6639ac6d" ON "bond_movement" ("agent_safe_id") `)
        await db.query(`CREATE TABLE "daily_service_funds" ("id" character varying NOT NULL, "day_timestamp" numeric NOT NULL, "olas_rewards_claimed" numeric NOT NULL, "cumulative_olas_rewards_claimed" numeric NOT NULL, "service_id" character varying, CONSTRAINT "PK_88ce7e29726a5eae451fedda66f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_service_funds_service_7b0d296f" ON "daily_service_funds" ("service_id") `)
        await db.query(`CREATE TABLE "service_nft_custody_change" ("id" character varying NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "service_id" character varying, CONSTRAINT "PK_e295bd62fcd0bc22088ba5c3e3e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_service_nft_custody_change_service_49de4177" ON "service_nft_custody_change" ("service_id") `)
        await db.query(`CREATE TABLE "service_index" ("id" character varying NOT NULL, "multisig" text NOT NULL, CONSTRAINT "PK_fac93289f8d51a3ee9c0ddcf961" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "pending_registration" ("id" character varying NOT NULL, "agent_ids" integer array NOT NULL, "operators" text array NOT NULL, CONSTRAINT "PK_63e892e181e9c3409e02ed84827" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "token" ("id" character varying NOT NULL, "symbol" text NOT NULL, "decimals" integer NOT NULL, CONSTRAINT "PK_82fae97f905930df5d62a702fc9" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "tracked_address" ("id" character varying NOT NULL, "role" text NOT NULL, "first_tracked_block" numeric NOT NULL, "master_safe_id" character varying, "service_id" character varying, CONSTRAINT "PK_349a2c920964b85ac73f30dd9f0" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_tracked_address_master_safe_c7f7f136" ON "tracked_address" ("master_safe_id") `)
        await db.query(`CREATE INDEX "idx_tracked_address_service_b9ff2a20" ON "tracked_address" ("service_id") `)
        await db.query(`CREATE TABLE "token_balance" ("id" character varying NOT NULL, "safe" text NOT NULL, "balance" numeric NOT NULL, "last_updated_timestamp" numeric NOT NULL, "last_updated_block" numeric NOT NULL, "token_id" character varying, CONSTRAINT "PK_dc23ea262a0188977523d90ae7f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_token_balance_token_63c52d93" ON "token_balance" ("token_id") `)
        await db.query(`CREATE TABLE "indexer_status" ("id" character varying NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, CONSTRAINT "PK_2a3644fefd70a0c04e4a744d4af" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "agent_safe" ADD CONSTRAINT "FK_d2d1108634cca5af4914504c8d9" FOREIGN KEY ("master_safe_id") REFERENCES "master_safe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "agent_safe" ADD CONSTRAINT "FK_0984b41ba36ecf499bf0b27fc24" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_31b823d7645ace0dc100bacff93" FOREIGN KEY ("master_safe_id") REFERENCES "master_safe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_d3b2d51a57719ce8a4175d2a77f" FOREIGN KEY ("agent_safe_id") REFERENCES "agent_safe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_56f59198dc7075bf82a7db7591d" FOREIGN KEY ("current_staking_contract_id") REFERENCES "staking_contract"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "agent_funding_event" ADD CONSTRAINT "FK_3d8f7c1ce9cec0dd8f7c099b0de" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "agent_funding_event" ADD CONSTRAINT "FK_eea2739fc2a4c5a288f6547b21b" FOREIGN KEY ("master_safe_id") REFERENCES "master_safe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "funds_movement" ADD CONSTRAINT "FK_b6fb06be221768cb9bd3d1caf16" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "funds_movement" ADD CONSTRAINT "FK_dc1e7b41859ace23a5c23ae03c9" FOREIGN KEY ("master_safe_id") REFERENCES "master_safe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "funds_movement" ADD CONSTRAINT "FK_f55980dc1335ee3470018e289bf" FOREIGN KEY ("agent_safe_id") REFERENCES "agent_safe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "funds_movement" ADD CONSTRAINT "FK_387649717ccef984dadb2387dda" FOREIGN KEY ("staking_contract_id") REFERENCES "staking_contract"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "funds_movement" ADD CONSTRAINT "FK_a39cba3ff34fb4305609397ab30" FOREIGN KEY ("agent_funding_event_id") REFERENCES "agent_funding_event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bond_movement" ADD CONSTRAINT "FK_c6335d2f28abcf9e81104a1790d" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bond_movement" ADD CONSTRAINT "FK_5838717fe64105f9dd9298b4fd8" FOREIGN KEY ("master_safe_id") REFERENCES "master_safe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bond_movement" ADD CONSTRAINT "FK_8d0c5d5950dd6810c7b921267a5" FOREIGN KEY ("agent_safe_id") REFERENCES "agent_safe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "daily_service_funds" ADD CONSTRAINT "FK_fee557b9c8ccac1246306a1ef9f" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "service_nft_custody_change" ADD CONSTRAINT "FK_8e8b4f3ca11a2a191000c157659" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "tracked_address" ADD CONSTRAINT "FK_87b2a87b51b3f5021f413757106" FOREIGN KEY ("master_safe_id") REFERENCES "master_safe"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "tracked_address" ADD CONSTRAINT "FK_81d048410dcde433ac60f326d9f" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "token_balance" ADD CONSTRAINT "FK_5813c3040e74c285719679c6935" FOREIGN KEY ("token_id") REFERENCES "token"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "token_balance" DROP CONSTRAINT "FK_5813c3040e74c285719679c6935"`)
        await db.query(`ALTER TABLE "tracked_address" DROP CONSTRAINT "FK_81d048410dcde433ac60f326d9f"`)
        await db.query(`ALTER TABLE "tracked_address" DROP CONSTRAINT "FK_87b2a87b51b3f5021f413757106"`)
        await db.query(`ALTER TABLE "service_nft_custody_change" DROP CONSTRAINT "FK_8e8b4f3ca11a2a191000c157659"`)
        await db.query(`ALTER TABLE "daily_service_funds" DROP CONSTRAINT "FK_fee557b9c8ccac1246306a1ef9f"`)
        await db.query(`ALTER TABLE "bond_movement" DROP CONSTRAINT "FK_8d0c5d5950dd6810c7b921267a5"`)
        await db.query(`ALTER TABLE "bond_movement" DROP CONSTRAINT "FK_5838717fe64105f9dd9298b4fd8"`)
        await db.query(`ALTER TABLE "bond_movement" DROP CONSTRAINT "FK_c6335d2f28abcf9e81104a1790d"`)
        await db.query(`ALTER TABLE "funds_movement" DROP CONSTRAINT "FK_a39cba3ff34fb4305609397ab30"`)
        await db.query(`ALTER TABLE "funds_movement" DROP CONSTRAINT "FK_387649717ccef984dadb2387dda"`)
        await db.query(`ALTER TABLE "funds_movement" DROP CONSTRAINT "FK_f55980dc1335ee3470018e289bf"`)
        await db.query(`ALTER TABLE "funds_movement" DROP CONSTRAINT "FK_dc1e7b41859ace23a5c23ae03c9"`)
        await db.query(`ALTER TABLE "funds_movement" DROP CONSTRAINT "FK_b6fb06be221768cb9bd3d1caf16"`)
        await db.query(`ALTER TABLE "agent_funding_event" DROP CONSTRAINT "FK_eea2739fc2a4c5a288f6547b21b"`)
        await db.query(`ALTER TABLE "agent_funding_event" DROP CONSTRAINT "FK_3d8f7c1ce9cec0dd8f7c099b0de"`)
        await db.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_56f59198dc7075bf82a7db7591d"`)
        await db.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_d3b2d51a57719ce8a4175d2a77f"`)
        await db.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_31b823d7645ace0dc100bacff93"`)
        await db.query(`ALTER TABLE "agent_safe" DROP CONSTRAINT "FK_0984b41ba36ecf499bf0b27fc24"`)
        await db.query(`ALTER TABLE "agent_safe" DROP CONSTRAINT "FK_d2d1108634cca5af4914504c8d9"`)
        await db.query(`DROP TABLE "indexer_status"`)
        await db.query(`DROP INDEX "public"."idx_token_balance_token_63c52d93"`)
        await db.query(`DROP TABLE "token_balance"`)
        await db.query(`DROP INDEX "public"."idx_tracked_address_service_b9ff2a20"`)
        await db.query(`DROP INDEX "public"."idx_tracked_address_master_safe_c7f7f136"`)
        await db.query(`DROP TABLE "tracked_address"`)
        await db.query(`DROP TABLE "token"`)
        await db.query(`DROP TABLE "pending_registration"`)
        await db.query(`DROP TABLE "service_index"`)
        await db.query(`DROP INDEX "public"."idx_service_nft_custody_change_service_49de4177"`)
        await db.query(`DROP TABLE "service_nft_custody_change"`)
        await db.query(`DROP INDEX "public"."idx_daily_service_funds_service_7b0d296f"`)
        await db.query(`DROP TABLE "daily_service_funds"`)
        await db.query(`DROP INDEX "public"."idx_bond_movement_agent_safe_6639ac6d"`)
        await db.query(`DROP INDEX "public"."idx_bond_movement_master_safe_46f5ecad"`)
        await db.query(`DROP INDEX "public"."idx_bond_movement_service_09b070cf"`)
        await db.query(`DROP TABLE "bond_movement"`)
        await db.query(`DROP INDEX "public"."idx_funds_movement_agent_funding_event_e58d176e"`)
        await db.query(`DROP INDEX "public"."idx_funds_movement_staking_contract_5b8e460e"`)
        await db.query(`DROP INDEX "public"."idx_funds_movement_agent_safe_8baac439"`)
        await db.query(`DROP INDEX "public"."idx_funds_movement_master_safe_e85e0274"`)
        await db.query(`DROP INDEX "public"."idx_funds_movement_service_00889d75"`)
        await db.query(`DROP TABLE "funds_movement"`)
        await db.query(`DROP INDEX "public"."idx_agent_funding_event_master_safe_6d6a8407"`)
        await db.query(`DROP INDEX "public"."idx_agent_funding_event_service_5b5efd90"`)
        await db.query(`DROP TABLE "agent_funding_event"`)
        await db.query(`DROP TABLE "master_safe"`)
        await db.query(`DROP INDEX "public"."idx_service_current_staking_contract_8fef2861"`)
        await db.query(`DROP INDEX "public"."idx_service_agent_safe_a2926dff"`)
        await db.query(`DROP INDEX "public"."idx_service_master_safe_8b79bdf7"`)
        await db.query(`DROP TABLE "service"`)
        await db.query(`DROP TABLE "staking_contract"`)
        await db.query(`DROP INDEX "public"."idx_agent_safe_service_c1d14b83"`)
        await db.query(`DROP INDEX "public"."idx_agent_safe_master_safe_15dfcbff"`)
        await db.query(`DROP TABLE "agent_safe"`)
    }
}
