type CreateMech @entity(immutable: false) {
  id: Bytes!
  mech: Bytes! # address
  agentId: BigInt! # uint256
  price: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type OwnerUpdated @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Pause @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Unpause @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Request @entity(immutable: false) {
  id: ID!
  sender: Sender!
  mech: Bytes! # address
  requestId: BigInt!
  ipfsHash: String!
  prompt: String
  tool: String
  questionTitle: String
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  delivery: Deliver @derivedFrom(field: "request")
  service: Service 
}

type Deliver @entity(immutable: true) {
  id: Bytes!
  sender: Bytes!
  mech: Bytes! # address
  requestId: BigInt!
  request: Request
  ipfsHash: String!
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
  service: Service
}

type Approval @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  spender: Bytes! # address
  AgentRegistry_id: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ApprovalForAll @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  operator: Bytes! # address
  approved: Boolean! # bool
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type BaseURIChanged @entity(immutable: true) {
  id: Bytes!
  baseURI: String! # string
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type CreateAgent @entity(immutable: true) {
  id: Bytes!
  agentId: BigInt! # uint256
  agentHash: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type ManagerUpdated @entity(immutable: true) {
  id: Bytes!
  manager: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type AgentRegistryOwnerUpdated @entity(immutable: true) {
  id: Bytes!
  owner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Transfer @entity(immutable: true) {
  id: Bytes!
  from: Bytes! # address
  to: Bytes! # address
  AgentRegistry_id: BigInt! # uint256
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UpdateAgentHash @entity(immutable: true) {
  id: Bytes!
  agentId: BigInt! # uint256
  agentHash: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type MechAgent @entity(immutable: false) {
  id: ID! # agent Id
  mech: Bytes # address
  address: Bytes # address
  agentHash: Bytes # bytes32
  service: Service
  totalTransactions: BigInt! 
  totalAtaTransactions: BigInt! 
}

type Sender @entity(immutable: false) {
  id: Bytes! # Address
  totalRequests: Int!
  totalTransactions: Int!
  totalAtaTransactions: Int!
  requests: [Request!] @derivedFrom(field: "sender")
}

type Global @entity(immutable: false) {
  id: ID! # uint256
  totalRequests: Int!
  totalDeliveries: Int!
  totalTransactions: Int!
  totalAtaTransactions: Int!
}

type CreateService @entity(immutable: true) {
  id: Bytes!
  serviceId: BigInt! # uint256
  configHash: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type UpdateService @entity(immutable: true) {
  id: Bytes!
  serviceId: BigInt! # uint256
  configHash: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type CreateMultisigWithAgents @entity(immutable: false) {
  id: Bytes!
  serviceId: BigInt! # uint256
  multisig: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type Service @entity(immutable: false) {
  id: ID! # serviceId
  serviceId: BigInt! # uint256
  configHash: Bytes # bytes32
  latestMultisig: Bytes # address
  historicalMultisigs: [Bytes!]! # array of addresses
  totalRequests: BigInt! # total number of requests
  totalDeliveries: BigInt! # total number of deliveries
  mechs: [MechAgent!]  @derivedFrom(field: "service")
  requests: [Request!] @derivedFrom(field: "service")
  deliveries: [Deliver!] @derivedFrom(field: "service")
}

type AgentMultisigAssociation @entity(immutable: false) {
  id: ID! # agentId
  agentId: BigInt! # uint256
  multisig: Bytes! # address
}