apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-db-service
  labels:
    io.service: {{ .Values.name }}-db-service
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.service: {{ .Values.name }}-db
