module.exports = class Data1789123592752 {
    name = 'Data1789123592752'

    async up(db) {
        await db.query(`CREATE TABLE "creator" ("id" character varying NOT NULL, CONSTRAINT "PK_43e489c9896f9eb32f7a0b912c2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "erc8004_metadata" ("id" character varying NOT NULL, "key" text NOT NULL, "value" text, "agent_id" character varying, CONSTRAINT "PK_77c0938f147ba698983fff2f96f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_erc8004_metadata_agent_bdf75f67" ON "erc8004_metadata" ("agent_id") `)
        await db.query(`CREATE TABLE "erc8004_agent" ("id" character varying NOT NULL, "agent_wallet" text, CONSTRAINT "PK_16ab911d9f6b915040a007268bc" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "service" ("id" character varying NOT NULL, "multisig" text, "agent_ids" integer array NOT NULL, "creation_timestamp" numeric NOT NULL, "config_hash" text, "creator_id" character varying, "erc8004_agent_id" character varying, CONSTRAINT "PK_85a21558c006647cd76fdce044b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_service_creator_7465f295" ON "service" ("creator_id") `)
        await db.query(`CREATE INDEX "idx_service_erc8004_agent_10abfe9e" ON "service" ("erc8004_agent_id") `)
        await db.query(`CREATE TABLE "agent_registration" ("id" character varying NOT NULL, "service_id" integer NOT NULL, "agent_id" integer NOT NULL, "registration_timestamp" numeric NOT NULL, CONSTRAINT "PK_fe9e53b3d7c9c05099ff0f45110" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "multisig" ("id" character varying NOT NULL, "service_id" integer NOT NULL, "creator" text NOT NULL, "creation_timestamp" numeric NOT NULL, "tx_hash" text NOT NULL, "agent_ids" integer array NOT NULL, CONSTRAINT "PK_ca0822446a16f9665878a4e3cb2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_multisig_service_id_0afa46ea" ON "multisig" ("service_id") `)
        await db.query(`CREATE TABLE "daily_service_activity" ("id" character varying NOT NULL, "day_timestamp" numeric NOT NULL, "agent_ids" integer array NOT NULL, "service_id" character varying, CONSTRAINT "PK_4c6ffcb23e1e58c464cb0595555" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_service_activity_service_d0c83930" ON "daily_service_activity" ("service_id") `)
        await db.query(`CREATE INDEX "idx_daily_service_activity_day_timestamp_e83a07ca" ON "daily_service_activity" ("day_timestamp") `)
        await db.query(`CREATE TABLE "agent_performance" ("id" character varying NOT NULL, "tx_count" numeric NOT NULL, CONSTRAINT "PK_bd380fd0820fb7f9c66a2e16656" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "daily_unique_agent" ("id" character varying NOT NULL, "daily_unique_agents_id" character varying, "agent_id" character varying, CONSTRAINT "PK_9f2b4b93332a056acc68decd50a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_unique_agent_daily_unique_agents_7066b717" ON "daily_unique_agent" ("daily_unique_agents_id") `)
        await db.query(`CREATE INDEX "idx_daily_unique_agent_agent_ba20201e" ON "daily_unique_agent" ("agent_id") `)
        await db.query(`CREATE TABLE "daily_unique_agents" ("id" character varying NOT NULL, "day_timestamp" numeric NOT NULL, "count" integer NOT NULL, CONSTRAINT "PK_90f8d88676fb304af5b889995ea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_unique_agents_day_timestamp_dcfe51fa" ON "daily_unique_agents" ("day_timestamp") `)
        await db.query(`CREATE TABLE "daily_agent_multisig" ("id" character varying NOT NULL, "daily_agent_performance_id" character varying, "multisig_id" character varying, CONSTRAINT "PK_05f311b0445025ca8babc681cfb" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_agent_multisig_daily_agent_performance_8bbbb356" ON "daily_agent_multisig" ("daily_agent_performance_id") `)
        await db.query(`CREATE INDEX "idx_daily_agent_multisig_multisig_ad83e981" ON "daily_agent_multisig" ("multisig_id") `)
        await db.query(`CREATE TABLE "daily_agent_performance" ("id" character varying NOT NULL, "day_timestamp" numeric NOT NULL, "agent_id" integer NOT NULL, "tx_count" integer NOT NULL, "active_multisig_count" integer NOT NULL, CONSTRAINT "PK_63eced69622a7b2c782a4fabac3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_agent_performance_day_timestamp_2b77c149" ON "daily_agent_performance" ("day_timestamp") `)
        await db.query(`CREATE INDEX "idx_daily_agent_performance_agent_id_16c6814a" ON "daily_agent_performance" ("agent_id") `)
        await db.query(`CREATE TABLE "daily_active_multisig" ("id" character varying NOT NULL, "daily_active_multisigs_id" character varying, "multisig_id" character varying, CONSTRAINT "PK_49c7694879ae294e3648fe74c65" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_active_multisig_daily_active_multisigs_f9aac03d" ON "daily_active_multisig" ("daily_active_multisigs_id") `)
        await db.query(`CREATE INDEX "idx_daily_active_multisig_multisig_a1f2ef0c" ON "daily_active_multisig" ("multisig_id") `)
        await db.query(`CREATE TABLE "daily_active_multisigs" ("id" character varying NOT NULL, "day_timestamp" numeric NOT NULL, "count" integer NOT NULL, CONSTRAINT "PK_ce224b24a22de7a12d191d174ad" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_active_multisigs_day_timestamp_9a19e0be" ON "daily_active_multisigs" ("day_timestamp") `)
        await db.query(`CREATE TABLE "global" ("id" character varying NOT NULL, "tx_count" numeric NOT NULL, "last_updated" numeric NOT NULL, "total_operators" integer NOT NULL, CONSTRAINT "PK_48e6c3f5b4e6caf50bc68644a00" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "operator" ("id" character varying NOT NULL, CONSTRAINT "PK_8b950e1572745d9f69be7748ae8" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "erc8004_metadata" ADD CONSTRAINT "FK_6d3dda7d79e4640319b20f002e9" FOREIGN KEY ("agent_id") REFERENCES "erc8004_agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_b01363ba7d1dd9f97b3ce3fe814" FOREIGN KEY ("creator_id") REFERENCES "creator"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_44fbb8a5be7a8c9e92b472076fe" FOREIGN KEY ("erc8004_agent_id") REFERENCES "erc8004_agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "daily_service_activity" ADD CONSTRAINT "FK_9ec825175efdf1c5daab2f16480" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "daily_unique_agent" ADD CONSTRAINT "FK_cc91108c7bfceba153f16917b2b" FOREIGN KEY ("daily_unique_agents_id") REFERENCES "daily_unique_agents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "daily_unique_agent" ADD CONSTRAINT "FK_d9d4fa03c5dba151b7fb63f4046" FOREIGN KEY ("agent_id") REFERENCES "agent_performance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "daily_agent_multisig" ADD CONSTRAINT "FK_e176f19946f1f96f6e53ec95ce6" FOREIGN KEY ("daily_agent_performance_id") REFERENCES "daily_agent_performance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "daily_agent_multisig" ADD CONSTRAINT "FK_d16095498a6f7e879bbdd44110a" FOREIGN KEY ("multisig_id") REFERENCES "multisig"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "daily_active_multisig" ADD CONSTRAINT "FK_ff8abea45d62aa6a67d8b9fce97" FOREIGN KEY ("daily_active_multisigs_id") REFERENCES "daily_active_multisigs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "daily_active_multisig" ADD CONSTRAINT "FK_2d73889eb116548708d60411cca" FOREIGN KEY ("multisig_id") REFERENCES "multisig"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "daily_active_multisig" DROP CONSTRAINT "FK_2d73889eb116548708d60411cca"`)
        await db.query(`ALTER TABLE "daily_active_multisig" DROP CONSTRAINT "FK_ff8abea45d62aa6a67d8b9fce97"`)
        await db.query(`ALTER TABLE "daily_agent_multisig" DROP CONSTRAINT "FK_d16095498a6f7e879bbdd44110a"`)
        await db.query(`ALTER TABLE "daily_agent_multisig" DROP CONSTRAINT "FK_e176f19946f1f96f6e53ec95ce6"`)
        await db.query(`ALTER TABLE "daily_unique_agent" DROP CONSTRAINT "FK_d9d4fa03c5dba151b7fb63f4046"`)
        await db.query(`ALTER TABLE "daily_unique_agent" DROP CONSTRAINT "FK_cc91108c7bfceba153f16917b2b"`)
        await db.query(`ALTER TABLE "daily_service_activity" DROP CONSTRAINT "FK_9ec825175efdf1c5daab2f16480"`)
        await db.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_44fbb8a5be7a8c9e92b472076fe"`)
        await db.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_b01363ba7d1dd9f97b3ce3fe814"`)
        await db.query(`ALTER TABLE "erc8004_metadata" DROP CONSTRAINT "FK_6d3dda7d79e4640319b20f002e9"`)
        await db.query(`DROP TABLE "operator"`)
        await db.query(`DROP TABLE "global"`)
        await db.query(`DROP INDEX "public"."idx_daily_active_multisigs_day_timestamp_9a19e0be"`)
        await db.query(`DROP TABLE "daily_active_multisigs"`)
        await db.query(`DROP INDEX "public"."idx_daily_active_multisig_multisig_a1f2ef0c"`)
        await db.query(`DROP INDEX "public"."idx_daily_active_multisig_daily_active_multisigs_f9aac03d"`)
        await db.query(`DROP TABLE "daily_active_multisig"`)
        await db.query(`DROP INDEX "public"."idx_daily_agent_performance_agent_id_16c6814a"`)
        await db.query(`DROP INDEX "public"."idx_daily_agent_performance_day_timestamp_2b77c149"`)
        await db.query(`DROP TABLE "daily_agent_performance"`)
        await db.query(`DROP INDEX "public"."idx_daily_agent_multisig_multisig_ad83e981"`)
        await db.query(`DROP INDEX "public"."idx_daily_agent_multisig_daily_agent_performance_8bbbb356"`)
        await db.query(`DROP TABLE "daily_agent_multisig"`)
        await db.query(`DROP INDEX "public"."idx_daily_unique_agents_day_timestamp_dcfe51fa"`)
        await db.query(`DROP TABLE "daily_unique_agents"`)
        await db.query(`DROP INDEX "public"."idx_daily_unique_agent_agent_ba20201e"`)
        await db.query(`DROP INDEX "public"."idx_daily_unique_agent_daily_unique_agents_7066b717"`)
        await db.query(`DROP TABLE "daily_unique_agent"`)
        await db.query(`DROP TABLE "agent_performance"`)
        await db.query(`DROP INDEX "public"."idx_daily_service_activity_day_timestamp_e83a07ca"`)
        await db.query(`DROP INDEX "public"."idx_daily_service_activity_service_d0c83930"`)
        await db.query(`DROP TABLE "daily_service_activity"`)
        await db.query(`DROP INDEX "public"."idx_multisig_service_id_0afa46ea"`)
        await db.query(`DROP TABLE "multisig"`)
        await db.query(`DROP TABLE "agent_registration"`)
        await db.query(`DROP INDEX "public"."idx_service_erc8004_agent_10abfe9e"`)
        await db.query(`DROP INDEX "public"."idx_service_creator_7465f295"`)
        await db.query(`DROP TABLE "service"`)
        await db.query(`DROP TABLE "erc8004_agent"`)
        await db.query(`DROP INDEX "public"."idx_erc8004_metadata_agent_bdf75f67"`)
        await db.query(`DROP TABLE "erc8004_metadata"`)
        await db.query(`DROP TABLE "creator"`)
    }
}
