apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autonolas-subgraph-db-claim
spec:
  storageClassName: {{ .Values.postgres.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
