enum packageType {
  custom
  protocol
  connection
  contract
  skill
  agent
  service
  unknown
}

type Unit @entity(immutable: false) {
  id: Bytes! # Unique ID for the record
  tokenId: BigInt! # Token ID of the minted component
  publicId: String! # Public ID of the package
  packageType: packageType! # Component type
  packageHash: String! # IPFS hash of the package
  image: String! # Image hash
  description: String! # Package description
  metadataHash: String! # Metadata file hash
  owner: String! # Owner address
  block: BigInt! # Block number
  txHash: String! # Transaction hash
}

type Service @entity(immutable: false) {
  id: Bytes! # Unique ID for the record
  serviceId: BigInt! # Service ID
  publicId: String! # Public ID of the package
  state: BigInt! # Current state of the service
  agentIds: [BigInt!] # List of agent IDs
  threshold: BigInt! # Threshold value
  securityDeposit: BigInt! # Security deposit
  numberOfInstances: BigInt! # Number of instances
  maxNumberOfInstances: BigInt! # Number of instances
  multisig: String! # Multisig address
  instances: [String!] # List of agent instances
  packageHash: String! # IPFS hash of the package
  metadataHash: String! # Metadata file hash
  description: String! # Package description
  owner: String! # Owner string
}

type Multisig @entity(immutable: true) {
  id: Bytes! # Multisig address
  service: Service!
}

type DailyActivity @entity(immutable: false) {
  id: String! # Day ID (day-{dayTimestamp})
  dayTimestamp: BigInt! # Unix timestamp of day start
  count: Int!
  services: [String!]! # List of Service IDs
}
