services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
    ports:
      - "23798:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
