module.exports = class Data1790687097590 {
    name = 'Data1790687097590'

    async up(db) {
        await db.query(`CREATE TABLE "instance_created" ("id" character varying NOT NULL, "sender" text NOT NULL, "instance" text NOT NULL, "implementation" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_2e47dffae630aebe9673f13213c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "instance_removed" ("id" character varying NOT NULL, "instance" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_2273b6ed9a3a21695694dbac9c7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "instance_status_changed" ("id" character varying NOT NULL, "instance" text NOT NULL, "is_enabled" boolean NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_0a7352e1005c0b649d5a0fe8a81" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "owner_updated" ("id" character varying NOT NULL, "owner" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_507f6dba51b83510add846d9f33" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "verifier_updated" ("id" character varying NOT NULL, "verifier" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_dc1a98c505a039cd75270fbc61b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "checkpoint" ("id" character varying NOT NULL, "epoch" numeric NOT NULL, "available_rewards" numeric NOT NULL, "service_ids" text array NOT NULL, "rewards" text array NOT NULL, "epoch_length" numeric NOT NULL, "block_number" numeric NOT NULL, "transaction_hash" text NOT NULL, "block_timestamp" numeric NOT NULL, "contract_address" text NOT NULL, CONSTRAINT "PK_fea86db187949398f8b614f730a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "deposit" ("id" character varying NOT NULL, "sender" text NOT NULL, "amount" numeric NOT NULL, "balance" numeric NOT NULL, "available_rewards" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_6654b4be449dadfd9d03a324b61" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "reward_claimed" ("id" character varying NOT NULL, "epoch" numeric NOT NULL, "service_id" numeric NOT NULL, "owner" text NOT NULL, "multisig" text NOT NULL, "nonces" text array NOT NULL, "reward" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_ba652f6718c9620a32db973d46b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "service_force_unstaked" ("id" character varying NOT NULL, "epoch" numeric NOT NULL, "service_id" numeric NOT NULL, "owner" text NOT NULL, "multisig" text NOT NULL, "nonces" text array NOT NULL, "reward" numeric NOT NULL, "available_rewards" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_2af538c2660d7559e0178043b34" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "service_inactivity_warning" ("id" character varying NOT NULL, "epoch" numeric NOT NULL, "service_id" numeric NOT NULL, "service_inactivity" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_9e34f8e2792606094385303a18d" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "service_staked" ("id" character varying NOT NULL, "epoch" numeric NOT NULL, "service_id" numeric NOT NULL, "owner" text NOT NULL, "multisig" text NOT NULL, "nonces" text array NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_d53ff96f1acc69a7f65fb283024" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "service_unstaked" ("id" character varying NOT NULL, "epoch" numeric NOT NULL, "service_id" numeric NOT NULL, "owner" text NOT NULL, "multisig" text NOT NULL, "nonces" text array NOT NULL, "reward" numeric NOT NULL, "available_rewards" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_08036766cccfc2e9daf3d62c4f8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "services_evicted" ("id" character varying NOT NULL, "epoch" numeric NOT NULL, "service_ids" text array NOT NULL, "owners" text array NOT NULL, "multisigs" text array NOT NULL, "service_inactivity" text array NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_22aac84e90389f2125f441c68bf" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "withdraw" ("id" character varying NOT NULL, "to" text NOT NULL, "amount" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_5c172f81689173f75bf5906ef22" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "staking_contract" ("id" character varying NOT NULL, "sender" text NOT NULL, "instance" text NOT NULL, "implementation" text NOT NULL, "staking_manager" text, "staking_token" text, "service_registry_token_utility" text, "version" text, "config_complete" boolean NOT NULL, "is_olas_staking" boolean NOT NULL, "events_indexed" boolean NOT NULL, "metadata_hash" text NOT NULL, "max_num_services" numeric NOT NULL, "rewards_per_second" numeric NOT NULL, "min_staking_deposit" numeric NOT NULL, "min_staking_duration" numeric NOT NULL, "max_num_inactivity_periods" numeric NOT NULL, "liveness_period" numeric NOT NULL, "time_for_emissions" numeric NOT NULL, "num_agent_instances" numeric NOT NULL, "agent_ids" text array NOT NULL, "threshold" numeric NOT NULL, "config_hash" text NOT NULL, "proxy_hash" text NOT NULL, "service_registry" text NOT NULL, "activity_checker" text NOT NULL, CONSTRAINT "PK_692a716f40eadb56ebf963eeee6" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "reward_update" ("id" character varying NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "type" text NOT NULL, "amount" numeric NOT NULL, CONSTRAINT "PK_34c7f050c9eff09415c1125d6ba" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "global" ("id" character varying NOT NULL, "cumulative_olas_staked" numeric NOT NULL, "cumulative_olas_unstaked" numeric NOT NULL, "current_olas_staked" numeric NOT NULL, "total_rewards" numeric NOT NULL, "total_rewards_claimed" numeric NOT NULL, "last_active_day_timestamp" numeric NOT NULL, CONSTRAINT "PK_48e6c3f5b4e6caf50bc68644a00" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "service_rewards_history" ("id" character varying NOT NULL, "epoch" numeric NOT NULL, "contract_address" text NOT NULL, "reward_amount" numeric NOT NULL, "checkpointed_at" numeric, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "service_id" character varying, "checkpoint_id" character varying, CONSTRAINT "PK_d68e8f42ac3afbeb0b2752de7f1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_service_rewards_history_service_3003be4e" ON "service_rewards_history" ("service_id") `)
        await db.query(`CREATE INDEX "idx_service_rewards_history_checkpoint_4df10410" ON "service_rewards_history" ("checkpoint_id") `)
        await db.query(`CREATE TABLE "service" ("id" character varying NOT NULL, "current_olas_staked" numeric NOT NULL, "current_stake_amount" numeric NOT NULL, "has_olas_stake" boolean NOT NULL, "olas_rewards_earned" numeric NOT NULL, "olas_rewards_claimed" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "latest_staking_contract" text, "total_epochs_participated" integer NOT NULL, "global_id" character varying, CONSTRAINT "PK_85a21558c006647cd76fdce044b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_service_global_7011ef20" ON "service" ("global_id") `)
        await db.query(`CREATE TABLE "active_service_epoch" ("id" character varying NOT NULL, "contract_address" text NOT NULL, "epoch" numeric NOT NULL, "active_service_ids" text array NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, CONSTRAINT "PK_3c66279be4e237e715f8b3bb7b2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "cumulative_daily_staking_global" ("id" character varying NOT NULL, "timestamp" numeric NOT NULL, "block" numeric NOT NULL, "total_rewards" numeric NOT NULL, "total_rewards_claimed" numeric NOT NULL, "num_services" integer NOT NULL, "median_cumulative_rewards" numeric NOT NULL, CONSTRAINT "PK_170607560382bdbb218de319b5a" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "service_rewards_history" ADD CONSTRAINT "FK_f93b2bd52944caddf9d79a8de05" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "service_rewards_history" ADD CONSTRAINT "FK_9c70d222c39c859ea273a4be31c" FOREIGN KEY ("checkpoint_id") REFERENCES "checkpoint"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "service" ADD CONSTRAINT "FK_815221d5eed4c377b9e4979941e" FOREIGN KEY ("global_id") REFERENCES "global"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "service" DROP CONSTRAINT "FK_815221d5eed4c377b9e4979941e"`)
        await db.query(`ALTER TABLE "service_rewards_history" DROP CONSTRAINT "FK_9c70d222c39c859ea273a4be31c"`)
        await db.query(`ALTER TABLE "service_rewards_history" DROP CONSTRAINT "FK_f93b2bd52944caddf9d79a8de05"`)
        await db.query(`DROP TABLE "cumulative_daily_staking_global"`)
        await db.query(`DROP TABLE "active_service_epoch"`)
        await db.query(`DROP INDEX "public"."idx_service_global_7011ef20"`)
        await db.query(`DROP TABLE "service"`)
        await db.query(`DROP INDEX "public"."idx_service_rewards_history_checkpoint_4df10410"`)
        await db.query(`DROP INDEX "public"."idx_service_rewards_history_service_3003be4e"`)
        await db.query(`DROP TABLE "service_rewards_history"`)
        await db.query(`DROP TABLE "global"`)
        await db.query(`DROP TABLE "reward_update"`)
        await db.query(`DROP TABLE "staking_contract"`)
        await db.query(`DROP TABLE "withdraw"`)
        await db.query(`DROP TABLE "services_evicted"`)
        await db.query(`DROP TABLE "service_unstaked"`)
        await db.query(`DROP TABLE "service_staked"`)
        await db.query(`DROP TABLE "service_inactivity_warning"`)
        await db.query(`DROP TABLE "service_force_unstaked"`)
        await db.query(`DROP TABLE "reward_claimed"`)
        await db.query(`DROP TABLE "deposit"`)
        await db.query(`DROP TABLE "checkpoint"`)
        await db.query(`DROP TABLE "verifier_updated"`)
        await db.query(`DROP TABLE "owner_updated"`)
        await db.query(`DROP TABLE "instance_status_changed"`)
        await db.query(`DROP TABLE "instance_removed"`)
        await db.query(`DROP TABLE "instance_created"`)
    }
}
