module.exports = class Data1789467657039 {
    name = 'Data1789467657039'

    async up(db) {
        await db.query(`CREATE TABLE "global" ("id" character varying NOT NULL, "total_fees_in_usd" numeric NOT NULL, "total_fees_out_usd" numeric NOT NULL, "total_drained_fees_usd" numeric NOT NULL, "total_olas_burned_raw" numeric NOT NULL, "total_olas_burned_usd" numeric NOT NULL, CONSTRAINT "PK_48e6c3f5b4e6caf50bc68644a00" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "mech" ("id" character varying NOT NULL, "total_fees_in_usd" numeric NOT NULL, "total_fees_out_usd" numeric NOT NULL, "total_fees_in_raw" numeric NOT NULL, "total_fees_out_raw" numeric NOT NULL, CONSTRAINT "PK_4bfc2ee5ef5ed6a966e6f114a65" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "mech_model" ("id" character varying NOT NULL, "model" text NOT NULL, "total_fees_in_usd" numeric NOT NULL, "total_fees_out_usd" numeric NOT NULL, "total_fees_in_raw" numeric NOT NULL, "total_fees_out_raw" numeric NOT NULL, "mech_id" character varying, CONSTRAINT "PK_e026a722189fc5bc6d24dc9fb42" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_mech_model_mech_1b2c8d0c" ON "mech_model" ("mech_id") `)
        await db.query(`CREATE INDEX "idx_mech_model_model_6b6a47b3" ON "mech_model" ("model") `)
        await db.query(`CREATE TABLE "mech_transaction" ("id" character varying NOT NULL, "type" text NOT NULL, "model" text NOT NULL, "amount_raw" numeric NOT NULL, "amount_usd" numeric NOT NULL, "timestamp" numeric NOT NULL, "block_number" numeric NOT NULL, "tx_hash" text NOT NULL, "delivery_rate" numeric, "balance" numeric, "rate_diff" numeric, "mech_id" character varying, CONSTRAINT "PK_70dcf626e1b784e68b82521f203" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_mech_transaction_mech_c49ad933" ON "mech_transaction" ("mech_id") `)
        await db.query(`CREATE INDEX "idx_mech_transaction_type_fddac534" ON "mech_transaction" ("type") `)
        await db.query(`CREATE INDEX "idx_mech_transaction_model_804f6db6" ON "mech_transaction" ("model") `)
        await db.query(`CREATE INDEX "idx_mech_transaction_timestamp_5c9edbfb" ON "mech_transaction" ("timestamp") `)
        await db.query(`CREATE TABLE "daily_totals" ("id" character varying NOT NULL, "date" integer NOT NULL, "total_fees_in_usd" numeric NOT NULL, "total_fees_out_usd" numeric NOT NULL, CONSTRAINT "PK_ed4b2185ff710793f07428e05b3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_totals_date_a54afc9a" ON "daily_totals" ("date") `)
        await db.query(`CREATE TABLE "mech_daily" ("id" character varying NOT NULL, "date" integer NOT NULL, "fees_in_usd" numeric NOT NULL, "fees_out_usd" numeric NOT NULL, "fees_in_raw" numeric NOT NULL, "fees_out_raw" numeric NOT NULL, "mech_id" character varying, CONSTRAINT "PK_1840bec71e5d6f71e6ff82e4731" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_mech_daily_mech_1a85de07" ON "mech_daily" ("mech_id") `)
        await db.query(`CREATE INDEX "idx_mech_daily_date_2ed95658" ON "mech_daily" ("date") `)
        await db.query(`CREATE TABLE "drain_totals" ("id" character varying NOT NULL, "model" text NOT NULL, "total_drained_raw" numeric NOT NULL, "total_drained_usd" numeric NOT NULL, CONSTRAINT "PK_29d65ee8b6685b7f97d858a991f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "drain_event" ("id" character varying NOT NULL, "model" text NOT NULL, "token" text NOT NULL, "amount_raw" numeric NOT NULL, "amount_usd" numeric NOT NULL, "timestamp" numeric NOT NULL, "block_number" numeric NOT NULL, "tx_hash" text NOT NULL, CONSTRAINT "PK_a857b00166b8265b7b726210fe8" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_drain_event_model_a573af36" ON "drain_event" ("model") `)
        await db.query(`CREATE INDEX "idx_drain_event_timestamp_bbd0e582" ON "drain_event" ("timestamp") `)
        await db.query(`CREATE TABLE "indexer_status" ("id" character varying NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, CONSTRAINT "PK_2a3644fefd70a0c04e4a744d4af" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "mech_model" ADD CONSTRAINT "FK_cdd837548cc7b6d9099968b7e11" FOREIGN KEY ("mech_id") REFERENCES "mech"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mech_transaction" ADD CONSTRAINT "FK_e3afbe0ad280ca58f9ce214c72d" FOREIGN KEY ("mech_id") REFERENCES "mech"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mech_daily" ADD CONSTRAINT "FK_74fac09b9bf6b890b2dd505455b" FOREIGN KEY ("mech_id") REFERENCES "mech"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "mech_daily" DROP CONSTRAINT "FK_74fac09b9bf6b890b2dd505455b"`)
        await db.query(`ALTER TABLE "mech_transaction" DROP CONSTRAINT "FK_e3afbe0ad280ca58f9ce214c72d"`)
        await db.query(`ALTER TABLE "mech_model" DROP CONSTRAINT "FK_cdd837548cc7b6d9099968b7e11"`)
        await db.query(`DROP TABLE "indexer_status"`)
        await db.query(`DROP INDEX "public"."idx_drain_event_timestamp_bbd0e582"`)
        await db.query(`DROP INDEX "public"."idx_drain_event_model_a573af36"`)
        await db.query(`DROP TABLE "drain_event"`)
        await db.query(`DROP TABLE "drain_totals"`)
        await db.query(`DROP INDEX "public"."idx_mech_daily_date_2ed95658"`)
        await db.query(`DROP INDEX "public"."idx_mech_daily_mech_1a85de07"`)
        await db.query(`DROP TABLE "mech_daily"`)
        await db.query(`DROP INDEX "public"."idx_daily_totals_date_a54afc9a"`)
        await db.query(`DROP TABLE "daily_totals"`)
        await db.query(`DROP INDEX "public"."idx_mech_transaction_timestamp_5c9edbfb"`)
        await db.query(`DROP INDEX "public"."idx_mech_transaction_model_804f6db6"`)
        await db.query(`DROP INDEX "public"."idx_mech_transaction_type_fddac534"`)
        await db.query(`DROP INDEX "public"."idx_mech_transaction_mech_c49ad933"`)
        await db.query(`DROP TABLE "mech_transaction"`)
        await db.query(`DROP INDEX "public"."idx_mech_model_model_6b6a47b3"`)
        await db.query(`DROP INDEX "public"."idx_mech_model_mech_1b2c8d0c"`)
        await db.query(`DROP TABLE "mech_model"`)
        await db.query(`DROP TABLE "mech"`)
        await db.query(`DROP TABLE "global"`)
    }
}
