module.exports = class Data1785828886179 {
    name = 'Data1785828886179'

    async up(db) {
        await db.query(`CREATE TABLE "trader_service" ("id" character varying NOT NULL, "multisig" text, CONSTRAINT "PK_cee1e0f4ac744096c59dcca3cc1" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "agent_instance" ("id" character varying NOT NULL, "service_id" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_69ff332de64f510071e90a86d87" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "market_metadata" ("id" character varying NOT NULL, "title" text NOT NULL, "outcomes" text array NOT NULL, "raw_ancillary_data" text NOT NULL, CONSTRAINT "PK_9ddd9abac510bc36a6804172cad" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "market_participant" ("id" character varying NOT NULL, "total_bets" integer NOT NULL, "total_traded" numeric NOT NULL, "total_traded_settled" numeric NOT NULL, "total_payout" numeric NOT NULL, "outcome_shares0" numeric NOT NULL, "outcome_shares1" numeric NOT NULL, "expected_payout" numeric NOT NULL, "settled" boolean NOT NULL, "created_at" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "trader_agent_id" character varying, "question_id" character varying, CONSTRAINT "PK_f4eb2bb1a68ccf1f590ee0a321b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_market_participant_trader_agent_2b028c23" ON "market_participant" ("trader_agent_id") `)
        await db.query(`CREATE INDEX "idx_market_participant_question_568c5119" ON "market_participant" ("question_id") `)
        await db.query(`CREATE TABLE "question" ("id" character varying NOT NULL, "question_id" text NOT NULL, "is_neg_risk" boolean NOT NULL, "market_id" text, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "metadata_id" character varying, CONSTRAINT "PK_21e5786aa0ea704ae185a79b2d5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_question_metadata_8ddf9689" ON "question" ("metadata_id") `)
        await db.query(`CREATE TABLE "daily_profit_statistic" ("id" character varying NOT NULL, "date" numeric NOT NULL, "total_bets" integer NOT NULL, "total_traded" numeric NOT NULL, "total_payout" numeric NOT NULL, "daily_traded_settled" numeric NOT NULL, "daily_profit" numeric NOT NULL, "profit_participants" text array NOT NULL, "trader_agent_id" character varying, CONSTRAINT "PK_045ed7e8dbe188afa27b0b41d49" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_daily_profit_statistic_trader_agent_293b2e72" ON "daily_profit_statistic" ("trader_agent_id") `)
        await db.query(`CREATE INDEX "idx_daily_profit_statistic_date_1e7af961" ON "daily_profit_statistic" ("date") `)
        await db.query(`CREATE TABLE "bet" ("id" character varying NOT NULL, "outcome_index" numeric NOT NULL, "amount" numeric NOT NULL, "shares" numeric NOT NULL, "is_buy" boolean NOT NULL, "counted_in_total" boolean NOT NULL, "counted_in_profit" boolean NOT NULL, "builder" text, "metadata" text, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "bettor_id" character varying, "question_id" character varying, "market_participant_id" character varying, "daily_statistic_id" character varying, CONSTRAINT "PK_4ceea2cdef435807614b8e17aed" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_bet_bettor_e6313900" ON "bet" ("bettor_id") `)
        await db.query(`CREATE INDEX "idx_bet_question_1a1f0dde" ON "bet" ("question_id") `)
        await db.query(`CREATE INDEX "idx_bet_market_participant_1ec0f619" ON "bet" ("market_participant_id") `)
        await db.query(`CREATE INDEX "idx_bet_daily_statistic_4b4e0ba0" ON "bet" ("daily_statistic_id") `)
        await db.query(`CREATE TABLE "trader_agent" ("id" character varying NOT NULL, "service_id" numeric NOT NULL, "first_participation" numeric, "last_active" numeric, "total_bets" integer NOT NULL, "total_traded" numeric NOT NULL, "total_traded_settled" numeric NOT NULL, "total_payout" numeric NOT NULL, "total_expected_payout" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_ed9febc076c226f9e1bdfc588c2" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "deposit_wallet" ("id" character varying NOT NULL, "agent_instance" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "trader_agent_id" character varying, CONSTRAINT "PK_324b905d682a76992d542b52a3e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_deposit_wallet_trader_agent_3e2a8bf0" ON "deposit_wallet" ("trader_agent_id") `)
        await db.query(`CREATE TABLE "question_id_to_condition_id" ("id" character varying NOT NULL, "oracle" text NOT NULL, "condition_id" text NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_7e7f0c66f16819af09623c4ac42" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "token_registry" ("id" character varying NOT NULL, "token_id" numeric NOT NULL, "condition_id" text NOT NULL, "outcome_index" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_3f30ca954c5a4334b9592feba7f" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "question_resolution" ("id" character varying NOT NULL, "winning_index" numeric NOT NULL, "settled_price" numeric NOT NULL, "payouts" text array NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "question_id" character varying, CONSTRAINT "PK_4c6c12e253e1802af8cbfcd5e20" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_question_resolution_question_03e9c2da" ON "question_resolution" ("question_id") `)
        await db.query(`CREATE TABLE "global" ("id" character varying NOT NULL, "total_trader_agents" integer NOT NULL, "total_active_trader_agents" integer NOT NULL, "total_bets" integer NOT NULL, "total_payout" numeric NOT NULL, "total_traded" numeric NOT NULL, "total_traded_settled" numeric NOT NULL, "total_expected_payout" numeric NOT NULL, "total_markets_participated" integer NOT NULL, CONSTRAINT "PK_48e6c3f5b4e6caf50bc68644a00" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "payout_redemption_entity" ("id" character varying NOT NULL, "condition_id" text NOT NULL, "payout_amount" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "redeemer_id" character varying, "question_id" character varying, CONSTRAINT "PK_1665a3ca156c8b154fb4c3ab79a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_payout_redemption_entity_redeemer_da4c5e50" ON "payout_redemption_entity" ("redeemer_id") `)
        await db.query(`CREATE INDEX "idx_payout_redemption_entity_question_cc4f14f1" ON "payout_redemption_entity" ("question_id") `)
        await db.query(`CREATE TABLE "market_participated" ("id" character varying NOT NULL, CONSTRAINT "PK_c677e72112c14515bde0856d2ba" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "market_participant" ADD CONSTRAINT "FK_f5504cc778c8964c717b83bc392" FOREIGN KEY ("trader_agent_id") REFERENCES "trader_agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "market_participant" ADD CONSTRAINT "FK_d49eccb70e820ce9f42583db688" FOREIGN KEY ("question_id") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "question" ADD CONSTRAINT "FK_8aad7b01bafd1e5b72058671328" FOREIGN KEY ("metadata_id") REFERENCES "market_metadata"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "daily_profit_statistic" ADD CONSTRAINT "FK_8f73e051afb32873e997f6c518f" FOREIGN KEY ("trader_agent_id") REFERENCES "trader_agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bet" ADD CONSTRAINT "FK_73bfdd7c7a65502824524283a11" FOREIGN KEY ("bettor_id") REFERENCES "trader_agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bet" ADD CONSTRAINT "FK_fbc5868ae0d18eb1cf513825d50" FOREIGN KEY ("question_id") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bet" ADD CONSTRAINT "FK_e2004cc97ea89060d007c4e7915" FOREIGN KEY ("market_participant_id") REFERENCES "market_participant"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "bet" ADD CONSTRAINT "FK_e9264746801855f63f2be3cbf1e" FOREIGN KEY ("daily_statistic_id") REFERENCES "daily_profit_statistic"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "deposit_wallet" ADD CONSTRAINT "FK_7b45904ab13c40ca624f2560886" FOREIGN KEY ("trader_agent_id") REFERENCES "trader_agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "question_resolution" ADD CONSTRAINT "FK_7264805b184143100dae4fcfe3c" FOREIGN KEY ("question_id") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "payout_redemption_entity" ADD CONSTRAINT "FK_b52d648d16f08b9e250cfb4e49b" FOREIGN KEY ("redeemer_id") REFERENCES "trader_agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "payout_redemption_entity" ADD CONSTRAINT "FK_4c7e3e722c5884bb815f505d4e3" FOREIGN KEY ("question_id") REFERENCES "question"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "payout_redemption_entity" DROP CONSTRAINT "FK_4c7e3e722c5884bb815f505d4e3"`)
        await db.query(`ALTER TABLE "payout_redemption_entity" DROP CONSTRAINT "FK_b52d648d16f08b9e250cfb4e49b"`)
        await db.query(`ALTER TABLE "question_resolution" DROP CONSTRAINT "FK_7264805b184143100dae4fcfe3c"`)
        await db.query(`ALTER TABLE "deposit_wallet" DROP CONSTRAINT "FK_7b45904ab13c40ca624f2560886"`)
        await db.query(`ALTER TABLE "bet" DROP CONSTRAINT "FK_e9264746801855f63f2be3cbf1e"`)
        await db.query(`ALTER TABLE "bet" DROP CONSTRAINT "FK_e2004cc97ea89060d007c4e7915"`)
        await db.query(`ALTER TABLE "bet" DROP CONSTRAINT "FK_fbc5868ae0d18eb1cf513825d50"`)
        await db.query(`ALTER TABLE "bet" DROP CONSTRAINT "FK_73bfdd7c7a65502824524283a11"`)
        await db.query(`ALTER TABLE "daily_profit_statistic" DROP CONSTRAINT "FK_8f73e051afb32873e997f6c518f"`)
        await db.query(`ALTER TABLE "question" DROP CONSTRAINT "FK_8aad7b01bafd1e5b72058671328"`)
        await db.query(`ALTER TABLE "market_participant" DROP CONSTRAINT "FK_d49eccb70e820ce9f42583db688"`)
        await db.query(`ALTER TABLE "market_participant" DROP CONSTRAINT "FK_f5504cc778c8964c717b83bc392"`)
        await db.query(`DROP TABLE "market_participated"`)
        await db.query(`DROP INDEX "public"."idx_payout_redemption_entity_question_cc4f14f1"`)
        await db.query(`DROP INDEX "public"."idx_payout_redemption_entity_redeemer_da4c5e50"`)
        await db.query(`DROP TABLE "payout_redemption_entity"`)
        await db.query(`DROP TABLE "global"`)
        await db.query(`DROP INDEX "public"."idx_question_resolution_question_03e9c2da"`)
        await db.query(`DROP TABLE "question_resolution"`)
        await db.query(`DROP TABLE "token_registry"`)
        await db.query(`DROP TABLE "question_id_to_condition_id"`)
        await db.query(`DROP INDEX "public"."idx_deposit_wallet_trader_agent_3e2a8bf0"`)
        await db.query(`DROP TABLE "deposit_wallet"`)
        await db.query(`DROP TABLE "trader_agent"`)
        await db.query(`DROP INDEX "public"."idx_bet_daily_statistic_4b4e0ba0"`)
        await db.query(`DROP INDEX "public"."idx_bet_market_participant_1ec0f619"`)
        await db.query(`DROP INDEX "public"."idx_bet_question_1a1f0dde"`)
        await db.query(`DROP INDEX "public"."idx_bet_bettor_e6313900"`)
        await db.query(`DROP TABLE "bet"`)
        await db.query(`DROP INDEX "public"."idx_daily_profit_statistic_date_1e7af961"`)
        await db.query(`DROP INDEX "public"."idx_daily_profit_statistic_trader_agent_293b2e72"`)
        await db.query(`DROP TABLE "daily_profit_statistic"`)
        await db.query(`DROP INDEX "public"."idx_question_metadata_8ddf9689"`)
        await db.query(`DROP TABLE "question"`)
        await db.query(`DROP INDEX "public"."idx_market_participant_question_568c5119"`)
        await db.query(`DROP INDEX "public"."idx_market_participant_trader_agent_2b028c23"`)
        await db.query(`DROP TABLE "market_participant"`)
        await db.query(`DROP TABLE "market_metadata"`)
        await db.query(`DROP TABLE "agent_instance"`)
        await db.query(`DROP TABLE "trader_service"`)
    }
}
