module.exports = class Data1789129718683 {
    name = 'Data1789129718683'

    async up(db) {
        await db.query(`CREATE TABLE "global" ("id" character varying NOT NULL, "total_mechs" numeric NOT NULL, "total_marketplace_requests" numeric NOT NULL, "total_marketplace_deliveries" numeric NOT NULL, "total_marketplace_deliveries_with_signatures" numeric NOT NULL, "total_requests" numeric NOT NULL, "total_deliveries" numeric NOT NULL, "total_transactions" numeric NOT NULL, "total_ata_transactions" numeric NOT NULL, "total_fees_paid_usd" numeric NOT NULL, CONSTRAINT "PK_48e6c3f5b4e6caf50bc68644a00" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "sender" ("id" character varying NOT NULL, "total_legacy_requests" numeric NOT NULL, "total_legacy_transactions" numeric NOT NULL, "total_legacy_ata_transactions" numeric NOT NULL, "total_marketplace_requests" numeric NOT NULL, "total_off_chain_requests" numeric NOT NULL, "total_fees_paid_usd" numeric NOT NULL, CONSTRAINT "PK_8b4c940381151ff7dfc1bc34e9a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "deliver_for_marketplace" ("id" character varying NOT NULL, "request_id" text NOT NULL, "request_id_bytes" text NOT NULL, "ipfs_hash_bytes" text, "mech_service_multisig" text, "delivery_rate" numeric, "is_marketplace" boolean, "is_off_chain" boolean, "deliver_id" character varying, CONSTRAINT "REL_c70087e0de61b7349c91cddbfc" UNIQUE ("deliver_id"), CONSTRAINT "PK_ace1802915683dcb530ff39a60e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "idx_deliver_for_marketplace_deliver_c307e38d" ON "deliver_for_marketplace" ("deliver_id") `)
        await db.query(`CREATE TABLE "deliver" ("id" character varying NOT NULL, "request_id_bytes" text NOT NULL, "sender" text NOT NULL, "mech" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "request_id" character varying, "service_id" character varying, CONSTRAINT "PK_4c71d3cf83816acf309a256350c" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_deliver_request_id_bytes_9fbabb82" ON "deliver" ("request_id_bytes") `)
        await db.query(`CREATE INDEX "idx_deliver_mech_e79ac8c7" ON "deliver" ("mech") `)
        await db.query(`CREATE INDEX "idx_deliver_request_cd231148" ON "deliver" ("request_id") `)
        await db.query(`CREATE INDEX "idx_deliver_block_timestamp_4a213a99" ON "deliver" ("block_timestamp") `)
        await db.query(`CREATE INDEX "idx_deliver_transaction_hash_23d8ce75" ON "deliver" ("transaction_hash") `)
        await db.query(`CREATE INDEX "idx_deliver_service_c76695ea" ON "deliver" ("service_id") `)
        await db.query(`CREATE TABLE "request_to_marketplace" ("id" character varying NOT NULL, "request_id_bytes" text NOT NULL, "ipfs_hash_bytes" text, "is_marketplace" boolean, "is_off_chain" boolean, "request_id" character varying, CONSTRAINT "REL_a5f23a72d0631ee77cd8ddfef8" UNIQUE ("request_id"), CONSTRAINT "PK_30f30d3a61b20cd33bc6b5330b3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE UNIQUE INDEX "idx_request_to_marketplace_request_00cb1917" ON "request_to_marketplace" ("request_id") `)
        await db.query(`CREATE TABLE "request" ("id" character varying NOT NULL, "mech" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, "is_delivered" boolean NOT NULL, "priority_mech" text, "delivered_by_mech" text, "fee_usd" numeric, "final_fee_usd" numeric, "fee_raw" numeric, "fee_unit" character varying(7), "sender_id" character varying, "service_id" character varying, CONSTRAINT "PK_167d324701e6867f189aed52e18" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_request_sender_9a823ad7" ON "request" ("sender_id") `)
        await db.query(`CREATE INDEX "idx_request_mech_2f071c7a" ON "request" ("mech") `)
        await db.query(`CREATE INDEX "idx_request_block_timestamp_fb797995" ON "request" ("block_timestamp") `)
        await db.query(`CREATE INDEX "idx_request_transaction_hash_fd580601" ON "request" ("transaction_hash") `)
        await db.query(`CREATE INDEX "idx_request_service_12b44acd" ON "request" ("service_id") `)
        await db.query(`CREATE TABLE "metadata" ("id" character varying NOT NULL, "service_id_raw" numeric NOT NULL, "mech" text, "metadata" text NOT NULL, "service_id" character varying, CONSTRAINT "PK_56b22355e89941b9792c04ab176" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_metadata_service_d020c7c9" ON "metadata" ("service_id") `)
        await db.query(`CREATE TABLE "mech" ("id" character varying NOT NULL, "address" text NOT NULL, "mech_factory" text NOT NULL, "config_hash" text, "owner" text NOT NULL, "total_deliveries_transactions" numeric NOT NULL, "received_requests" numeric NOT NULL, "self_delivered_from_received" numeric NOT NULL, "delivered_by_others_from_received" numeric NOT NULL, "max_delivery_rate" numeric, "max_delivery_rate_usd" numeric, "karma" numeric NOT NULL, "payment_type" text NOT NULL, "service_id" character varying, CONSTRAINT "REL_2956c082e0ca5a1486056b01bb" UNIQUE ("service_id"), CONSTRAINT "PK_4bfc2ee5ef5ed6a966e6f114a65" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_mech_address_74fa810f" ON "mech" ("address") `)
        await db.query(`CREATE UNIQUE INDEX "idx_mech_service_4619f4c5" ON "mech" ("service_id") `)
        await db.query(`CREATE TABLE "service" ("id" character varying NOT NULL, "service_id" numeric NOT NULL, "config_hash" text, "latest_multisig" text, "historical_multisigs" text array NOT NULL, "total_requests" numeric NOT NULL, "total_deliveries" numeric NOT NULL, "agent_ids" integer array NOT NULL, CONSTRAINT "PK_85a21558c006647cd76fdce044b" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_service_service_id_b8ec8acf" ON "service" ("service_id") `)
        await db.query(`CREATE INDEX "idx_service_latest_multisig_fb126181" ON "service" ("latest_multisig") `)
        await db.query(`CREATE TABLE "requests_per_agent" ("id" character varying NOT NULL, "requests_count" numeric NOT NULL, CONSTRAINT "PK_8c4bf7ec105afed5843b9db2789" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "create_mech" ("id" character varying NOT NULL, "mech" text NOT NULL, "source" character varying(11), "service_id" numeric, "mech_factory" text, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_056d10e879e29979b9733f6fdf7" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_create_mech_service_id_a4715971" ON "create_mech" ("service_id") `)
        await db.query(`CREATE TABLE "create_multisig_with_agents" ("id" character varying NOT NULL, "service_id" numeric NOT NULL, "multisig" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_daa7b41fdbeb2393269ec83caea" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_create_multisig_with_agents_service_id_791bb1e6" ON "create_multisig_with_agents" ("service_id") `)
        await db.query(`CREATE TABLE "ata_transaction" ("id" character varying NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, CONSTRAINT "PK_82da6f3fc794843381bbf95dfc3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE TABLE "marketplace_request" ("id" character varying NOT NULL, "priority_mech" text NOT NULL, "requester" text NOT NULL, "num_requests" numeric NOT NULL, "request_ids" text array NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_2cc61048ee17e2cf1511f5077b5" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_marketplace_request_requester_f175360c" ON "marketplace_request" ("requester") `)
        await db.query(`CREATE INDEX "idx_marketplace_request_block_timestamp_027fe6e3" ON "marketplace_request" ("block_timestamp") `)
        await db.query(`CREATE TABLE "marketplace_delivery" ("id" character varying NOT NULL, "delivery_mech" text NOT NULL, "num_deliveries" numeric NOT NULL, "request_ids" text array NOT NULL, "delivered_requests" boolean array NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_8689be4ab9f8b1f4bc85f25d989" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_marketplace_delivery_delivery_mech_327af687" ON "marketplace_delivery" ("delivery_mech") `)
        await db.query(`CREATE INDEX "idx_marketplace_delivery_block_timestamp_6c04a1ae" ON "marketplace_delivery" ("block_timestamp") `)
        await db.query(`CREATE TABLE "marketplace_delivery_with_signatures" ("id" character varying NOT NULL, "delivery_mech" text NOT NULL, "requester" text NOT NULL, "num_deliveries" numeric NOT NULL, "request_ids" text array NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_1f35db9f57a51eda455f5c13502" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_marketplace_delivery_with_signatures_delivery_mech_138aab18" ON "marketplace_delivery_with_signatures" ("delivery_mech") `)
        await db.query(`CREATE INDEX "idx_marketplace_delivery_with_signatures_requester_a95149a4" ON "marketplace_delivery_with_signatures" ("requester") `)
        await db.query(`CREATE INDEX "idx_marketplace_delivery_with_signatures_block_timesta_de894cec" ON "marketplace_delivery_with_signatures" ("block_timestamp") `)
        await db.query(`CREATE TABLE "create_service" ("id" character varying NOT NULL, "service_id" numeric NOT NULL, "config_hash" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_3a7d3078cfb02edf874e8daf402" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_create_service_service_id_a8095784" ON "create_service" ("service_id") `)
        await db.query(`CREATE TABLE "update_service" ("id" character varying NOT NULL, "service_id" numeric NOT NULL, "config_hash" text NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_801bfcf3f1322706019224de754" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_update_service_service_id_0cc3eb12" ON "update_service" ("service_id") `)
        await db.query(`CREATE TABLE "register_instance" ("id" character varying NOT NULL, "operator" text NOT NULL, "service_id" numeric NOT NULL, "agent_instance" text NOT NULL, "agent_id" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_dcfd59737c837827250d8fdd749" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_register_instance_service_id_543b5367" ON "register_instance" ("service_id") `)
        await db.query(`CREATE INDEX "idx_register_instance_agent_instance_0a5e7d53" ON "register_instance" ("agent_instance") `)
        await db.query(`CREATE TABLE "terminate_service" ("id" character varying NOT NULL, "service_id" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_1e944cb548447bd97a0d9209dba" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_terminate_service_service_id_5fade47e" ON "terminate_service" ("service_id") `)
        await db.query(`CREATE TABLE "transfer" ("id" character varying NOT NULL, "from" text NOT NULL, "to" text NOT NULL, "service_id" numeric NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, "transaction_hash" text NOT NULL, CONSTRAINT "PK_fd9ddbdd49a17afcbe014401295" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "idx_transfer_service_id_36af1abf" ON "transfer" ("service_id") `)
        await db.query(`CREATE TABLE "indexer_status" ("id" character varying NOT NULL, "block_number" numeric NOT NULL, "block_timestamp" numeric NOT NULL, CONSTRAINT "PK_2a3644fefd70a0c04e4a744d4af" PRIMARY KEY ("id"))`)
        await db.query(`ALTER TABLE "deliver_for_marketplace" ADD CONSTRAINT "FK_c70087e0de61b7349c91cddbfc9" FOREIGN KEY ("deliver_id") REFERENCES "deliver"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "deliver" ADD CONSTRAINT "FK_f541e52d3f65ba3cf4506430248" FOREIGN KEY ("request_id") REFERENCES "request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "deliver" ADD CONSTRAINT "FK_c0d393b6f665cee1d53b147e921" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "request_to_marketplace" ADD CONSTRAINT "FK_a5f23a72d0631ee77cd8ddfef86" FOREIGN KEY ("request_id") REFERENCES "request"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "request" ADD CONSTRAINT "FK_5ae23b096b55625fdc81d591950" FOREIGN KEY ("sender_id") REFERENCES "sender"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "request" ADD CONSTRAINT "FK_de9b81f6d230f01c4b094f216db" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "metadata" ADD CONSTRAINT "FK_e6e19a422a150ce066edebcf556" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
        await db.query(`ALTER TABLE "mech" ADD CONSTRAINT "FK_2956c082e0ca5a1486056b01bb7" FOREIGN KEY ("service_id") REFERENCES "service"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`)
    }

    async down(db) {
        await db.query(`ALTER TABLE "mech" DROP CONSTRAINT "FK_2956c082e0ca5a1486056b01bb7"`)
        await db.query(`ALTER TABLE "metadata" DROP CONSTRAINT "FK_e6e19a422a150ce066edebcf556"`)
        await db.query(`ALTER TABLE "request" DROP CONSTRAINT "FK_de9b81f6d230f01c4b094f216db"`)
        await db.query(`ALTER TABLE "request" DROP CONSTRAINT "FK_5ae23b096b55625fdc81d591950"`)
        await db.query(`ALTER TABLE "request_to_marketplace" DROP CONSTRAINT "FK_a5f23a72d0631ee77cd8ddfef86"`)
        await db.query(`ALTER TABLE "deliver" DROP CONSTRAINT "FK_c0d393b6f665cee1d53b147e921"`)
        await db.query(`ALTER TABLE "deliver" DROP CONSTRAINT "FK_f541e52d3f65ba3cf4506430248"`)
        await db.query(`ALTER TABLE "deliver_for_marketplace" DROP CONSTRAINT "FK_c70087e0de61b7349c91cddbfc9"`)
        await db.query(`DROP TABLE "indexer_status"`)
        await db.query(`DROP INDEX "public"."idx_transfer_service_id_36af1abf"`)
        await db.query(`DROP TABLE "transfer"`)
        await db.query(`DROP INDEX "public"."idx_terminate_service_service_id_5fade47e"`)
        await db.query(`DROP TABLE "terminate_service"`)
        await db.query(`DROP INDEX "public"."idx_register_instance_agent_instance_0a5e7d53"`)
        await db.query(`DROP INDEX "public"."idx_register_instance_service_id_543b5367"`)
        await db.query(`DROP TABLE "register_instance"`)
        await db.query(`DROP INDEX "public"."idx_update_service_service_id_0cc3eb12"`)
        await db.query(`DROP TABLE "update_service"`)
        await db.query(`DROP INDEX "public"."idx_create_service_service_id_a8095784"`)
        await db.query(`DROP TABLE "create_service"`)
        await db.query(`DROP INDEX "public"."idx_marketplace_delivery_with_signatures_block_timesta_de894cec"`)
        await db.query(`DROP INDEX "public"."idx_marketplace_delivery_with_signatures_requester_a95149a4"`)
        await db.query(`DROP INDEX "public"."idx_marketplace_delivery_with_signatures_delivery_mech_138aab18"`)
        await db.query(`DROP TABLE "marketplace_delivery_with_signatures"`)
        await db.query(`DROP INDEX "public"."idx_marketplace_delivery_block_timestamp_6c04a1ae"`)
        await db.query(`DROP INDEX "public"."idx_marketplace_delivery_delivery_mech_327af687"`)
        await db.query(`DROP TABLE "marketplace_delivery"`)
        await db.query(`DROP INDEX "public"."idx_marketplace_request_block_timestamp_027fe6e3"`)
        await db.query(`DROP INDEX "public"."idx_marketplace_request_requester_f175360c"`)
        await db.query(`DROP TABLE "marketplace_request"`)
        await db.query(`DROP TABLE "ata_transaction"`)
        await db.query(`DROP INDEX "public"."idx_create_multisig_with_agents_service_id_791bb1e6"`)
        await db.query(`DROP TABLE "create_multisig_with_agents"`)
        await db.query(`DROP INDEX "public"."idx_create_mech_service_id_a4715971"`)
        await db.query(`DROP TABLE "create_mech"`)
        await db.query(`DROP TABLE "requests_per_agent"`)
        await db.query(`DROP INDEX "public"."idx_service_latest_multisig_fb126181"`)
        await db.query(`DROP INDEX "public"."idx_service_service_id_b8ec8acf"`)
        await db.query(`DROP TABLE "service"`)
        await db.query(`DROP INDEX "public"."idx_mech_service_4619f4c5"`)
        await db.query(`DROP INDEX "public"."idx_mech_address_74fa810f"`)
        await db.query(`DROP TABLE "mech"`)
        await db.query(`DROP INDEX "public"."idx_metadata_service_d020c7c9"`)
        await db.query(`DROP TABLE "metadata"`)
        await db.query(`DROP INDEX "public"."idx_request_service_12b44acd"`)
        await db.query(`DROP INDEX "public"."idx_request_transaction_hash_fd580601"`)
        await db.query(`DROP INDEX "public"."idx_request_block_timestamp_fb797995"`)
        await db.query(`DROP INDEX "public"."idx_request_mech_2f071c7a"`)
        await db.query(`DROP INDEX "public"."idx_request_sender_9a823ad7"`)
        await db.query(`DROP TABLE "request"`)
        await db.query(`DROP INDEX "public"."idx_request_to_marketplace_request_00cb1917"`)
        await db.query(`DROP TABLE "request_to_marketplace"`)
        await db.query(`DROP INDEX "public"."idx_deliver_service_c76695ea"`)
        await db.query(`DROP INDEX "public"."idx_deliver_transaction_hash_23d8ce75"`)
        await db.query(`DROP INDEX "public"."idx_deliver_block_timestamp_4a213a99"`)
        await db.query(`DROP INDEX "public"."idx_deliver_request_cd231148"`)
        await db.query(`DROP INDEX "public"."idx_deliver_mech_e79ac8c7"`)
        await db.query(`DROP INDEX "public"."idx_deliver_request_id_bytes_9fbabb82"`)
        await db.query(`DROP TABLE "deliver"`)
        await db.query(`DROP INDEX "public"."idx_deliver_for_marketplace_deliver_c307e38d"`)
        await db.query(`DROP TABLE "deliver_for_marketplace"`)
        await db.query(`DROP TABLE "sender"`)
        await db.query(`DROP TABLE "global"`)
    }
}
