name: Deploy Subgraphs to Production

on:
  release:
    types: [published]

jobs:
  # Deploy Mech Subgraph
  mech:
    uses: ./.github/workflows/deploy-subgraph-reusable.yml
    with:
      subgraph_name: mech
      working_directory: subgraphs/mech
      manifest_file: subgraph.yaml
      version: ${{ github.event.release.tag_name }}
    secrets:
      GRAPH_NODE_USER: ${{ secrets.GRAPH_NODE_PROD_USER }}
      GRAPH_NODE_PASSWORD: ${{ secrets.GRAPH_NODE_PROD_PASSWORD }}

  # Deploy Mech Marketplace for Base Network Subgraph
  mech-marketplace-base:
    uses: ./.github/workflows/deploy-subgraph-reusable.yml
    with:
      subgraph_name: mech-marketplace-base
      working_directory: subgraphs/mech-marketplace
      manifest_file: subgraph.base.yaml
      version: ${{ github.event.release.tag_name }}
    secrets:
      GRAPH_NODE_USER: ${{ secrets.GRAPH_NODE_PROD_USER }}
      GRAPH_NODE_PASSWORD: ${{ secrets.GRAPH_NODE_PROD_PASSWORD }}

  # Deploy Mech Marketplace for Gnosis Network Subgraph
  mech-marketplace-gnosis:
    uses: ./.github/workflows/deploy-subgraph-reusable.yml
    with:
      subgraph_name: mech-marketplace-gnosis
      working_directory: subgraphs/mech-marketplace
      manifest_file: subgraph.gnosis.yaml
      version: ${{ github.event.release.tag_name }}
    secrets:
      GRAPH_NODE_USER: ${{ secrets.GRAPH_NODE_PROD_USER }}
      GRAPH_NODE_PASSWORD: ${{ secrets.GRAPH_NODE_PROD_PASSWORD }}
