name: Deploy Subgraphs to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy'
        required: true
        type: string

jobs:
  # Deploy Mech Subgraph
  mech:
    uses: ./.github/workflows/deploy-subgraph-reusable.yml
    with:
      subgraph_name: mech
      working_directory: subgraphs/mech
      manifest_file: subgraph.yaml
      version: ${{ inputs.version }}
    secrets:
      GRAPH_NODE_USER: ${{ secrets.GRAPH_NODE_PROD_USER }}
      GRAPH_NODE_PASSWORD: ${{ secrets.GRAPH_NODE_PROD_PASSWORD }}

  # Deploy Service Registry Subgraph on the Mode Mainnet Network
  service-registry-mode-mainnet:
    uses: ./.github/workflows/deploy-subgraph-reusable.yml
    with:
      subgraph_name: service-registry-mode-mainnet
      working_directory: subgraphs/service-registry
      manifest_file: subgraph.mode-mainnet.yaml
      version: ${{ inputs.version }}
    secrets:
      GRAPH_NODE_USER: ${{ secrets.GRAPH_NODE_PROD_USER }}
      GRAPH_NODE_PASSWORD: ${{ secrets.GRAPH_NODE_PROD_PASSWORD }}
