name: Deploy Subgraphs

on:
  release:
    types: [published]

jobs:
  # Deploy Mech Marketplace for Base Network Subgraph
  deploy-mech-marketplace-base:
    uses: ./.github/workflows/deploy-subgraph-reusable.yml
    with:
      subgraph_name: mech-marketplace-base
      working_directory: subgraphs/mech-marketplace
      manifest_file: subgraph.base.yaml
      version: ${{ github.event.release.tag_name }}
    secrets:
      GRAPH_NODE_USER: ${{ secrets.GRAPH_NODE_PROD_USER }}
      GRAPH_NODE_PASSWORD: ${{ secrets.GRAPH_NODE_PROD_PASSWORD }}

  # Deploy Mech Marketplace for Gnosis Network Subgraph
  deploy-mech-marketplace-gnosis:
    uses: ./.github/workflows/deploy-subgraph-reusable.yml
    with:
      subgraph_name: mech-marketplace-gnosis
      working_directory: subgraphs/mech-marketplace
      manifest_file: subgraph.gnosis.yaml
      version: ${{ github.event.release.tag_name }}
    secrets:
      GRAPH_NODE_USER: ${{ secrets.GRAPH_NODE_PROD_USER }}
      GRAPH_NODE_PASSWORD: ${{ secrets.GRAPH_NODE_PROD_PASSWORD }}
